local M = {}

-- neovim terminal mode colors
local function set_terminal_colors(colors)
  -- vim.g.terminal_color_0 = colors.bg0
  -- vim.g.terminal_color_8 = colors.gray
  -- vim.g.terminal_color_1 = colors.neutral_red
  -- vim.g.terminal_color_9 = colors.red
  -- vim.g.terminal_color_2 = colors.neutral_green
  -- vim.g.terminal_color_10 = colors.green
  -- vim.g.terminal_color_3 = colors.neutral_yellow
  -- vim.g.terminal_color_11 = colors.yellow
  -- vim.g.terminal_color_4 = colors.neutral_blue
  -- vim.g.terminal_color_12 = colors.blue
  -- vim.g.terminal_color_5 = colors.neutral_purple
  -- vim.g.terminal_color_13 = colors.purple
  -- vim.g.terminal_color_6 = colors.neutral_aqua
  -- vim.g.terminal_color_14 = colors.aqua
  -- vim.g.terminal_color_7 = colors.fg4
  -- vim.g.terminal_color_15 = colors.fg1
end

M.setup = function()
  local config = require("medieval").config
  local palette = require("medieval.palette").palette
  set_terminal_colors(palette)

  local groups = {
    -- Base groups
    MedievalBaseBlue = { fg = palette.basementBlue },
    MedievalBlack = { fg = palette.basicallyBlack },
    MedievalTan = { fg = palette.traditionalTan },
    MedievalTanBold = { fg = palette.traditionalTan, bold = config.bold }, -- ModeMsg
    MedievalPurple = { fg = palette.prettyPurple },
    MedievalRoyalBlue = { fg = palette.boldRoyalBlue },
    MedievalRoyalBlueBold = { fg = palette.boldRoyalBlue, bold = config.bold },
    MedievalRoyalRed = { fg = palette.royaleRed },
    MedievalRoyalRedBold = { fg = palette.royaleRed, bold = config.bold },
    MedievalBlue = { fg = palette.boringBlue },
    MedievalGreen = { fg = palette.gleefulGreen },
    MedievalGreenBold = { fg = palette.gleefulGreen, bold = config.bold },
    MedievalLightGreen = { fg = palette.giantGreen },
    MedievalLightGreenBold = { fg = palette.giantGreen, bold = config.bold },
    MedievalElectricBlue = { fg = palette.electricBlue },
    MedievalElectricBlueBold = { fg = palette.electricBlue, bold = config.bold },
    MedievalSlightlySilver = { fg = palette.slightlySilver },
    MedievalSilver = { fg = palette.semiSilver },
    MedievalSilverBold = { fg = palette.semiSilver, bold = config.bold },
    MedievalBronze = { fg = palette.broBronze },
    MedievalWhite = { fg = palette.willingWhite },
    MedievalWhiteBold = { fg = palette.willingWhite, bold = config.bold },
    MedievalCursorBG = { bg = "#91ADDC" },
    MedievalCursorFG = { bg = "#00000C" },
    None = { fg = palette.none },

    MedievalRoyalRedSign = config.transparent_mode and { fg = palette.royaleRed, reverse = config.invert_signs }
      or { fg = palette.royaleRed, bg = palette.basicallyBlack, reverse = config.invert_signs },
    MedievalGreenSign = config.transparent_mode and { fg = palette.gleefulGreen, reverse = config.invert_signs }
      or { fg = palette.gleefulGreen, bg = palette.basicallyBlack, reverse = config.invert_signs },
    MedievalTanSign = config.transparent_mode and { fg = palette.none, reverse = config.invert_signs } -- diag-warn
      or { fg = palette.traditionalTan, bg = palette.basicallyBlack, reverse = config.invert_signs },
    MedievalBlueSign = config.transparent_mode and { fg = palette.none, reverse = config.invert_signs }
      or { fg = palette.none, bg = palette.none, reverse = config.invert_signs },
    MedievalSlightSilverSign = config.transparent_mode and { fg = palette.slightlySilver, reverse = config.invert_signs }
      or { fg = palette.slightlySilver, bg = palette.basementBlue, reverse = config.invert_signs },
    MedievalTanUnderline = { undercurl = config.undercurl, sp = palette.traditionalTan },

    -- HL groups start here
    Normal = config.transparent_mode and { fg = palette.traditionalTan, bg = nil } or { fg = palette.traditionalTan, bg = palette.basicallyBlack },
    NormalFloat = config.transparent_mode and { fg = palette.traditionalTan, bg = nil } or { fg = palette.traditionalTan, bg = palette.basicallyBlack },
    NormalNC = config.dim_inactive and { fg = palette.traditionalTan, bg = palette.basicallyBlack } or { link = "Normal" },
    CursorLine = { bg = palette.basementBlue }, -- Might need an option to 'disable' this
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = palette.willingWhite, bg = palette.basicallyBlack, reverse = config.invert_tabline },
    TabLineSel = { fg = palette.willingWhite, bg = palette.basicallyBlack, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    MatchParen = { fg = palette.willingWhite, bg = palette.boringBlue, bold = config.bold },
    ColorColumn = { bg = palette.basicallyBlack },
    Conceal = { fg = palette.prettyPurple },
    CursorLineNr = { fg = palette.broBronze, bg = palette.basicallyBlack, bold = true },
    NonText = { link = "MedievalBaseBlue" },
    SpecialKey = { link = "MedievalRoyalRed" },
    Visual = { fg = palette.willingWhite, bg = palette.boringBlue, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = palette.electricBlue, bg = palette.basicallyBlack, reverse = config.inverse },
    IncSearch = { fg = palette.electricBlue, bg = palette.basicallyBlack, reverse = config.inverse },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { fg = palette.traditionalTan, bg = palette.basicallyBlack, bold = config.bold },
    Underlined = { fg = palette.giantGreen, underline = config.underline },
    Statusline = { reverse = config.inverse, bold = true },
    StatusLineInsert = { fg = palette.basicallyBlack, bg = palette.giantGreen, bold = true },
    StatusLineVisual = { fg = palette.basicallyBlack, bg = palette.boldRoyalBlue, bold = true },
    StatusLineReplace = { fg = palette.basicallyBlack, bg = palette.broBronze, bold = true },
    StatusLineCmdLine = { fg = palette.basicallyBlack, bg = palette.prettyPurple, bold = true },
    StatusLineNC = { fg = palette.basicallyBlack, bg = palette.basicallyBlack, reverse = config.inverse },
    WinBar = { link = "Normal" },
    WinBarNC = { link = "NormalNC" },
    WinSeparator = config.transparent_mode and { fg = palette.semiSilver, bg = nil } or { fg = palette.semiSilver, bg = palette.basicallyBlack },
    WildMenu = { fg = palette.traditionalTan, bg = palette.basicallyBlack, bold = config.bold },
    Directory = { link = "MedievalBlueBold" },  -- @unknown
    Title = { link = "MedievalGreen" },
    ErrorMsg = { fg = palette.royaleRed, bg = palette.basicallyBlack, bold = config.bold },
    MoreMsg = { link = "MedievalWhiteBold" },
    ModeMsg = { link = "MedievalWhiteBold" },
    Question = { link = "MedievalRoyalBlueBold" },
    WarningMsg = { link = "MedievalRoyalRedBold" },
    LineNr = { link = "MedievalSilver" },
    SignColumn = config.transparent_mode and { bg = nil } or { bg = palette.basicallyBlack },
    Folded = { fg = palette.giantGreen, bg = palette.semiSilver, italic = config.italic.folds },
    FoldColumn = config.transparent_mode and { fg = palette.traditionalTan, bg = nil } or { fg = palette.traditionalTan, bg = palette.willingWhite }, -- IDK
    Cursor = { bg = palette.traditionalTan, fg = palette.basicallyBlack },
    vCursor = { link = "Cursor" },
    iCursor = { bg = palette.gleefulGreen },
    lCursor = { link = "Cursor" },
    Special = { fg = palette.boldRoyalBlue }, --@Link
    Delimiter = { link = "MedievalRoyalRed" }, -- Make option?
    Comment = { fg = palette.slightlySilver, italic = config.italic.comments },
    Todo = { fg = palette.none, bold = config.bold, italic = config.italic.comments }, -- IDK
    Done = { fg = palette.electricBlue, bold = config.bold, italic = config.italic.comments }, -- IDK
    Error = { fg = palette.royaleRed, bold = config.bold, reverse = config.inverse }, -- IDK
    Statement = { link = "MedievalRoyalBlue" },
    Conditional = { link = "MedievalRoyalBlue" },
    Repeat = { link = "MedievalRoyalBlue" },
    Label = { link = "MedievalRoyalBlue" },
    Exception = { link = "MedievalRoyalBlue" },
    Operator = { fg = palette.royaleRed, italic = config.italic.operators },
    Keyword = { link = "MedievalWhite" },
    Identifier = { link = "MedievalBlue" },
    Function = { link = "MedievalGreen" },
    PreProc = { link = "MedievalPurple" },
    Include = { link = "MedievalPurple" },
    Define = { link = "MedievalPurple" },
    Macro = { link = "MedievalPurple" },
    PreCondit = { link = "MedievalPurple" },
    Constant = { link = "MedievalElectricBlue" },
    Character = { link = "MedievalLightGreen" },
    String = { fg = palette.giantGreen, italic = config.italic.strings },
    Boolean = { link = "MedievalElectricBlue" },
    Number = { link = "MedievalElectricBlue" },
    Float = { link = "MedievalElectricBlue" },
    Type = { link = "MedievalRoyalBlue" },
    StorageClass = { link = "MedievalRoyalBlue" },
    Structure = { link = "MedievalPurple" },
    Typedef = { link = "MedievalRoyalBlue" },
    Tag = { link = "MedievalGreen" },
    Pmenu = { fg = palette.traditionalTan, bg = palette.basicallyBlack },
    PmenuSel = { fg = palette.traditionalTan, bg = palette.semiSilver, bold = config.bold },
    PmenuSbar = { bg = palette.basicallyBlack },
    PmenuThumb = { bg = palette.gleefulGreen },
    DiffDelete = { fg = palette.royaleRed, bg = palette.basicallyBlack, reverse = config.inverse },
    DiffAdd = { fg = palette.gleefulGreen, bg = palette.basicallyBlack, reverse = config.inverse },
    DiffChange = { fg = palette.boldRoyalBlue, bg = palette.basicallyBlack, reverse = config.inverse },
    DiffText = { fg = palette.traditionalTan, bg = palette.basicallyBlack, reverse = config.inverse },
    SpellCap = { link = "MedievalBlueUnderline" },
    SpellBad = { link = "MedievalRoyalRedUnderline" },
    SpellLocal = { link = "None" }, -- @unknown
    SpellRare = { link = "MedievalLightGreenUnderline" },
    Whitespace = { fg = palette.willingWhite },
    -- LSP SEMHL
    ["@lsp.type.comment"] = { link = "Comment" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.type.parameter"] = { link = "@variable" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.type"] = { link = "@type" },
    -- C/Cpp
    ["@lsp.type.class.cpp"] = { link = "Type" },
    ["@lsp.type.enum.cpp"] = { link = "Type" },
    -- ["@lsp.mod.filescope.cpp"] = { link = "@function" },
    -- ["@lsp.typemod.macro.globalscope.cpp"] = { link = "@keyword" },
    -- TS
    ["@lsp.type.namespace.typescriptreact"] = { link = "MedievalBronze" },
    ["@lsp.type.interface.typescriptreact"] = { link = "@type" },
    ["@lsp.typemod.variable.defaultLibrary.typescriptreact"] = { link = "MedievalPurple" },
    -- ["@lsp.mod.defaultLibrary.typescriptreact"] = { link = "MedievalPurple" },
    -- ["@lsp.type.class"] = { fg = "#FFF3B2" },
    -- ["@lsp.type.class"] = { fg = "#FFEB7F" },
    -- ["@lsp.type.class"] = { fg = palette.boldRoyalBlue },
    -- ["@lsp.type.keyword"] = { link = "Comment" },
    -- Zig
    -- ["@lsp.type.type.zig"] = { link = "MedievalTan" },
    ["@keyword.exception.zig"] = { link = "MedievalRoyalRed" },
    -- LSP Diagnostic
    DiagnosticError = { link = "MedievalRoyalRed" },
    DiagnosticSignError = { link = "MedievalRoyalRedSign" },
    DiagnosticUnderlineError = { link = "MedievalRoyalRedUnderline" },
    DiagnosticWarn = { link = "MedievalTanSign" },
    DiagnosticSignWarn = { link = "MedievalTanSign" },
    DiagnosticUnderlineWarn = { link = "MedievalTanUnderline" },
    DiagnosticInfo = { link = "MedievalBlue" },
    DiagnosticSignInfo = { link = "MedievalBlueSign" },
    DiagnosticUnderlineInfo = { link = "MedievalBlueUnderline" },
    DiagnosticHint = { link = "MedievalPurple" },
    DiagnosticSignHint = { link = "MedievalTanSign" },
    DiagnosticUnderlineHint = { link = "MedievalPurpleUnderline" },
    DiagnosticFloatingError = { link = "MedievalRoyalRed" },
    DiagnosticFloatingWarn = { link = "MedievalTan" },
    DiagnosticFloatingInfo = { link = "MedievalBlue" },
    DiagnosticFloatingHint = { link = "MedievalPurple" },
    DiagnosticVirtualTextError = { link = "MedievalRoyalRed" },
    DiagnosticVirtualTextWarn = { link = "MedievalTan" },
    DiagnosticVirtualTextInfo = { link = "MedievalBlue" },
    DiagnosticVirtualTextHint = { link = "MedievalPurple" },
    LspReferenceRead = { link = "MedievalWhiteBold" },
    LspReferenceText = { link = "MedievalWhiteBold" },
    LspReferenceWrite = { link = "None" },
    LspCodeLens = { link = "None" },
    LspSignatureActiveParameter = { fg = palette.none, bold = true },
    -- semantic token
    -- adapted from https://github.com/jdrouhard/neovim/blob/9f035559defd9d575f37fd825954610065d9cf96/src/nvim/highlight_group.c#L267
    ["@decorator"] = { link = "Identifier" },
    ["@enum"] = { link = "@constructor" },
    ["@enumMember"] = { link = "Number" },
    ["@event"] = { link = "Identifier" },
    ["@interface"] = { link = "Identifier" },
    ["@modifier"] = { link = "Identifier" },
    ["@regexp"] = { link = "SpecialChar" },
    ["@struct"] = { link = "@constructor" },
    ["@typeParameter"] = { link = "Type" },
    -- nvim-treesitter (0.8 compat)
    -- Adapted from https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f#commitcomment-87014462
    ["@annotation"] = { link = "Operator" },
    ["@comment"] = { link = "Comment" },
    ["@none"] = { bg = "NONE", fg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "MedievalBronze" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.escape"] = { link = "MedievalBronze" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.call"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.macro"] = { link = "Macro" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Function" },
    ["@constructor.lua"] = { link = "MedievalSlightlySilverBold" },
    ["@parameter"] = { link = "@lsp.type.parameter" },
    ["@keyword"] = { link = "Keyword" },
    -- ["@keyword.repeat"] = { link = "MedievalRoyalBlue" },
    -- ["@keyword.conditional"] = { link = "MedievalRoyalBlue" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.qualifier"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "MedievalPurple" },
    ["@property"] = { link = "Identifier" },
    ["@variable"] = { link = "MedievalTan" },
    ["@variable.builtin"] = { link = "Special" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@namespace"] = { link = "MedievalTan" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "MedievalTan" },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.unchecked"] = { link = "Todo" },
    ["@text.todo.checked"] = { link = "Done" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },

    -- nvim-treesitter (0.8 overrides)
    ["@text.strong"] = { bold = config.bold },
    ["@text.strike"] = { strikethrough = config.strikethrough },
    ["@text.emphasis"] = { italic = config.italic.strings },
    ["@text.underline"] = { underline = config.underline },
    ["@keyword.operator"] = { link = "MedievalRoyalBlue" },
    -- gitcommit
    gitcommitSelectedFile = { link = "None" },
    gitcommitDiscardedFile = { link = "MedievalRoyalRed" },
    -- gitsigns.nvim
    GitSignsAdd = { link = "MedievalGreenSign" },
    GitSignsChange = { link = "MedievalTanSign" },
    GitSignsDelete = { link = "MedievalRoyalRedSign" },
    -- FIXME: handle nones like the ones below
    -- nvim-tree
    NvimTreeSymlink = { fg = palette.none_aqua },
    NvimTreeRootFolder = { fg = palette.none_purple, bold = true },
    NvimTreeFolderIcon = { fg = palette.none_blue, bold = true },
    NvimTreeFileIcon = { fg = palette.none },
    NvimTreeExecFile = { fg = palette.none_green, bold = true },
    NvimTreeOpenedFile = { fg = palette.none_red, bold = true },
    NvimTreeSpecialFile = { fg = palette.none_yellow, bold = true, underline = true },
    NvimTreeImageFile = { fg = palette.none_purple },
    NvimTreeIndentMarker = { fg = palette.none },
    NvimTreeGitDirty = { fg = palette.none_yellow },
    NvimTreeGitStaged = { fg = palette.none_yellow },
    NvimTreeGitMerge = { fg = palette.none_purple },
    NvimTreeGitRenamed = { fg = palette.none_purple },
    NvimTreeGitNew = { fg = palette.none_yellow },
    NvimTreeGitDeleted = { fg = palette.none_red },
    NvimTreeWindowPicker = { bg = palette.none_aqua },
    -- termdebug
    debugPC = { bg = palette.none_blue },
    debugBreakpoint = { link = "MedievalRoyalRedSign" },
    -- vim-startify
    StartifyBracket = { link = "None" },
    StartifyFile = { link = "MedievalTan" },
    StartifyNumber = { link = "MedievalBlue" },
    StartifyPath = { link = "None" },
    StartifySlash = { link = "None" },
    StartifySection = { link = "MedievalRoyalBlue" },
    StartifySpecial = { link = "None" },
    StartifyHeader = { link = "None" },
    StartifyFooter = { link = "None" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    -- vim-dirvish
    DirvishPathTail = { link = "MedievalPurple" },
    DirvishArg = { link = "MedievalRoyalBlue" },
    -- FIXME: Correct netrw stuff
    -- netrw
    netrwDir = { link = "MedievalPurple" },
    netrwClassify = { link = "MedievalPurple" },
    netrwLink = { link = "None" },
    netrwSymLink = { link = "MedievalTan" },
    netrwExe = { link = "MedievalRoyalBlue" },
    netrwComment = { link = "None" },
    netrwList = { link = "MedievalBlue" },
    netrwHelpCmd = { link = "MedievalPurple" },
    netrwCmdSep = { link = "None" },
    netrwVersion = { link = "None" },
    -- nerdtree
    NERDTreeDir = { link = "MedievalPurple" },
    NERDTreeDirSlash = { link = "MedievalPurple" },
    NERDTreeOpenable = { link = "None" },
    NERDTreeClosable = { link = "None" },
    NERDTreeFile = { link = "MedievalTan" },
    NERDTreeExecFile = { link = "MedievalRoyalBlue" },
    NERDTreeUp = { link = "None" },
    NERDTreeCWD = { link = "None" },
    NERDTreeHelp = { link = "MedievalTan" },
    NERDTreeToggleOn = { link = "None" },
    NERDTreeToggleOff = { link = "MedievalRoyalRed" },
    -- coc.nvim
    CocErrorSign = { link = "MedievalRoyalRedSign" },
    CocWarningSign = { link = "None" },
    CocInfoSign = { link = "MedievalBlueSign" },
    CocHintSign = { link = "MedievalTanSign" },
    CocErrorFloat = { link = "MedievalRoyalRed" },
    CocWarningFloat = { link = "None" },
    CocInfoFloat = { link = "MedievalBlue" },
    CocHintFloat = { link = "MedievalPurple" },
    CocDiagnosticsError = { link = "MedievalRoyalRed" },
    CocDiagnosticsWarning = { link = "None" },
    CocDiagnosticsInfo = { link = "MedievalBlue" },
    CocDiagnosticsHint = { link = "MedievalPurple" },
    CocSelectedText = { link = "MedievalRoyalRed" },
    CocMenuSel = { link = "PmenuSel" },
    CocCodeLens = { link = "None" },
    CocErrorHighlight = { link = "MedievalRoyalRedUnderline" },
    CocWarningHighlight = { link = "None" },
    CocInfoHighlight = { link = "MedievalBlueUnderline" },
    CocHintHighlight = { link = "MedievalPurpleUnderline" },
    -- telescope
    TelescopeNormal = { link = "MedievalSilver" },
    TelescopeSelection = { link = "MedievalTan" },
    TelescopeSelectionCaret = { link = "MedievalRoyalRed" },
    TelescopeMultiSelection = { link = "MedievalElectricBlue" },
    TelescopeBorder = { link = "MedievalTan" },
    TelescopePromptBorder = { link = "MedievalTan" },
    TelescopeResultsBorder = { link = "MedievalTan" },
    TelescopePreviewBorder = { link = "MedievalTan" },
    TelescopeMatching = { link = "MedievalElectricBlue" },
    TelescopePromptPrefix = { link = "MedievalRoyalRed" },
    TelescopePrompt = { link = "MedievalTan" },
    TelescopePromptNormal = { link = "MedievalTan" },
    TelescopePromptCounter = { link = "MedievalElectricBlue" },
    -- nvim-cmp
    CmpItemAbbr = { link = "MedievalTan" },
    CmpItemAbbrDeprecated = { link = "None" },
    CmpItemAbbrMatch = { link = "MedievalBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "MedievalBlueUnderline" },
    CmpItemMenu = { link = "MedievalTan" },
    CmpItemKindText = { link = "MedievalTan" },
    CmpItemKindVariable = { link = "MedievalTan" },
    CmpItemKindMethod = { link = "MedievalGreen" },
    CmpItemKindFunction = { link = "MedievalGreen" },
    CmpItemKindConstructor = { link = "MedievalBronze" },
    CmpItemKindUnit = { link = "MedievalBlue" },
    CmpItemKindField = { link = "MedievalBlue" },
    CmpItemKindClass = { link = "MedievalBronze" },
    CmpItemKindInterface = { link = "MedievalRoyalBlue" },
    CmpItemKindModule = { link = "MedievalRoyalBlue" },
    CmpItemKindProperty = { link = "MedievalBlue" },
    CmpItemKindValue = { link = "MedievalLightGreen" },
    CmpItemKindEnum = { link = "MedievalRoyalBlue" },
    CmpItemKindOperator = { link = "MedievalRoyalRed" },
    CmpItemKindKeyword = { link = "MedievalRoyalBlue" },
    CmpItemKindEvent = { link = "MedievalElectricBlue" },
    CmpItemKindReference = { link = "MedievalElectricBlue" },
    CmpItemKindColor = { link = "MedievalElectricBlue" },
    CmpItemKindSnippet = { link = "MedievalElectricBlue" },
    CmpItemKindFile = { link = "MedievalTan" },
    CmpItemKindFolder = { link = "MedievalBronze" },
    CmpItemKindEnumMember = { link = "MedievalBlue" },
    CmpItemKindConstant = { link = "MedievalElectricBlue" },
    CmpItemKindStruct = { link = "MedievalBronze" },
    CmpItemKindTypeParameter = { link = "MedievalRoyalBlue" },
    diffAdded = { link = "MedievalLightGreen" },
    diffRemoved = { link = "MedievalRoyalRed" },
    diffChanged = { link = "MedievalBronze" },
    diffFile = { link = "MedievalWhite" },
    diffNewFile = { link = "MedievalRoyalBlue" },
    diffOldFile = { link = "MedievalPurple" },
    diffLine = { link = "MedievalBlue" },
    diffIndexLine = { link = "diffChanged" },
    -- navic (highlight icons)
    NavicIconsFile = { link = "MedievalBlue" },
    NavicIconsModule = { link = "None" },
    NavicIconsNamespace = { link = "MedievalBlue" },
    NavicIconsPackage = { link = "MedievalPurple" },
    NavicIconsClass = { link = "MedievalRoyalBlue" },
    NavicIconsMethod = { link = "MedievalBlue" },
    NavicIconsProperty = { link = "MedievalPurple" },
    NavicIconsField = { link = "MedievalLightGreen" },
    NavicIconsConstructor = { link = "MedievalBlue" },
    NavicIconsEnum = { link = "MedievalLightGreen" },
    NavicIconsInterface = { link = "None" },
    NavicIconsFunction = { link = "MedievalBlue" },
    NavicIconsVariable = { link = "MedievalLightGreen" },
    NavicIconsConstant = { link = "None" },
    NavicIconsString = { link = "None" },
    NavicIconsNumber = { link = "None" },
    NavicIconsBoolean = { link = "None" },
    NavicIconsArray = { link = "None" },
    NavicIconsObject = { link = "None" },
    NavicIconsKey = { link = "MedievalPurple" },
    NavicIconsNull = { link = "None" },
    NavicIconsEnumMember = { link = "MedievalRoyalBlue" },
    NavicIconsStruct = { link = "MedievalLightGreen" },
    NavicIconsEvent = { link = "MedievalRoyalBlue" },
    NavicIconsOperator = { link = "MedievalRoyalRed" },
    NavicIconsTypeParameter = { link = "MedievalRoyalRed" },
    NavicText = { link = "MedievalWhite" },
    NavicSeparator = { link = "MedievalWhite" },
    -- FIXME: Make this prob
    -- html
    htmlTag = { link = "MedievalPurpleBold" },
    htmlEndTag = { link = "MedievalPurpleBold" },
    htmlTagName = { link = "MedievalBlue" },
    htmlArg = { link = "None" },
    htmlTagN = { link = "MedievalTan" },
    htmlSpecialTagName = { link = "MedievalBlue" },
    htmlLink = { fg = palette.giantGreen, underline = config.underline },
    htmlSpecialChar = { link = "MedievalRoyalBlue" },
    htmlBold = { fg = palette.none, bg = palette.none, bold = config.bold },
    htmlBoldUnderline = { fg = palette.none, bg = palette.none, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { fg = palette.none, bg = palette.none, bold = config.bold, italic = true },
    htmlBoldUnderlineItalic = {
      fg = palette.none,
      bg = palette.none,
      bold = config.bold,
      italic = true,
      underline = config.underline,
    },
    htmlUnderline = { fg = palette.none, bg = palette.none, underline = config.underline },
    htmlUnderlineItalic = {
      fg = palette.none,
      bg = palette.none,
      italic = true,
      underline = config.underline,
    },
    htmlItalic = { fg = palette.none, bg = palette.none, italic = true },
    -- xml
    xmlTag = { link = "MedievalPurpleBold" },
    xmlEndTag = { link = "MedievalPurpleBold" },
    xmlTagName = { link = "MedievalBlue" },
    xmlEqual = { link = "MedievalBlue" },
    docbkKeyword = { link = "MedievalPurpleBold" },
    xmlDocTypeDecl = { link = "None" },
    xmlDocTypeKeyword = { link = "MedievalLightGreen" },
    xmlCdataStart = { link = "None" },
    xmlCdataCdata = { link = "MedievalLightGreen" },
    dtdFunction = { link = "None" },
    dtdTagName = { link = "MedievalLightGreen" },
    xmlAttrib = { link = "None" },
    xmlProcessingDelim = { link = "None" },
    dtdParamEntityPunct = { link = "None" },
    dtdParamEntityDPunct = { link = "None" },
    xmlAttribPunct = { link = "None" },
    xmlEntity = { link = "MedievalRoyalBlue" },
    xmlEntityPunct = { link = "MedievalRoyalBlue" },
    -- clojure
    clojureKeyword = { link = "MedievalBlue" },
    clojureCond = { link = "None" },
    clojureSpecial = { link = "None" },
    clojureDefine = { link = "None" },
    clojureFunc = { link = "MedievalRoyalBlue" },
    clojureRepeat = { link = "MedievalRoyalBlue" },
    clojureCharacter = { link = "MedievalPurple" },
    clojureStringEscape = { link = "MedievalPurple" },
    clojureException = { link = "MedievalRoyalBlue" },
    clojureRegexp = { link = "MedievalPurple" },
    clojureRegexpEscape = { link = "MedievalPurple" },
    clojureRegexpCharClass = { fg = palette.none, bold = config.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "None" },
    clojureAnonArg = { link = "MedievalRoyalBlue" },
    clojureVariable = { link = "MedievalBlue" },
    clojureMacro = { link = "None" },
    clojureMeta = { link = "MedievalRoyalBlue" },
    clojureDeref = { link = "MedievalRoyalBlue" },
    clojureQuote = { link = "MedievalRoyalBlue" },
    clojureUnquote = { link = "MedievalRoyalBlue" },
    -- C
    cOperator = { link = "MedievalLightGreen" },
    cppOperator = { link = "MedievalLightGreen" },
    cStructure = { link = "Type" },
    -- python
    pythonBuiltin = { link = "None" },
    pythonBuiltinObj = { link = "None" },
    pythonBuiltinFunc = { link = "None" },
    pythonFunction = { link = "MedievalPurple" },
    pythonDecorator = { link = "MedievalRoyalBlue" },
    pythonInclude = { link = "MedievalBlue" },
    pythonImport = { link = "MedievalBlue" },
    pythonRun = { link = "MedievalBlue" },
    pythonCoding = { link = "MedievalBlue" },
    pythonOperator = { link = "MedievalRoyalBlue" },
    pythonException = { link = "MedievalRoyalRed" },
    pythonExceptions = { link = "MedievalLightGreen" },
    pythonBoolean = { link = "MedievalLightGreen" },
    pythonDot = { link = "None" },
    pythonConditional = { link = "MedievalRoyalBlue" },
    pythonRepeat = { link = "MedievalRoyalBlue" },
    pythonDottedName = { link = "None" },
    -- CSS
    cssBraces = { link = "MedievalBlue" },
    cssFunctionName = { link = "MedievalRoyalBlue" },
    cssIdentifier = { link = "None" },
    cssClassName = { link = "None" },
    cssColor = { link = "MedievalBlue" },
    cssSelectorOp = { link = "MedievalBlue" },
    cssSelectorOp2 = { link = "MedievalBlue" },
    cssImportant = { link = "None" },
    cssVendor = { link = "MedievalTan" },
    cssTextProp = { link = "MedievalPurple" },
    cssAnimationProp = { link = "MedievalPurple" },
    cssUIProp = { link = "MedievalRoyalBlue" },
    cssTransformProp = { link = "MedievalPurple" },
    cssTransitionProp = { link = "MedievalPurple" },
    cssPrintProp = { link = "MedievalPurple" },
    cssPositioningProp = { link = "MedievalRoyalBlue" },
    cssBoxProp = { link = "MedievalPurple" },
    cssFontDescriptorProp = { link = "MedievalPurple" },
    cssFlexibleBoxProp = { link = "MedievalPurple" },
    cssBorderOutlineProp = { link = "MedievalPurple" },
    cssBackgroundProp = { link = "MedievalPurple" },
    cssMarginProp = { link = "MedievalPurple" },
    cssListProp = { link = "MedievalPurple" },
    cssTableProp = { link = "MedievalPurple" },
    cssFontProp = { link = "MedievalPurple" },
    cssPaddingProp = { link = "MedievalPurple" },
    cssDimensionProp = { link = "MedievalPurple" },
    cssRenderProp = { link = "MedievalPurple" },
    cssColorProp = { link = "MedievalPurple" },
    cssGeneratedContentProp = { link = "MedievalPurple" },
    -- javascript
    javaScriptBraces = { link = "MedievalWhite" },
    javaScriptFunction = { link = "MedievalPurple" },
    javaScriptIdentifier = { link = "MedievalRoyalBlue" },
    javaScriptMember = { link = "MedievalBlue" },
    javaScriptNumber = { link = "MedievalLightGreen" },
    javaScriptNull = { link = "MedievalLightGreen" },
    javaScriptParens = { link = "None" },
    -- typescript
    typescriptReserved = { link = "MedievalPurple" },
    typescriptLabel = { link = "MedievalPurple" },
    typescriptFuncKeyword = { link = "MedievalPurple" },
    typescriptFuncType = { link = "MedievalTan" },
    typescriptParenthesizedType = { link = "MedievalRoyalRed" },
    typescriptConditionalType = { link = "MedievalRoyalRed" },
    typescriptFuncTypeArrow = { link = "MedievalRoyalRed" },
    typescriptArrowFunc = { link = "MedievalRoyalRed" },
    typescriptTypeAnnotation = { link = "MedievalRoyalRed" },
    typescriptIdentifier = { link = "None" },
    typescriptBraces = { link = "MedievalWhite" },
    typescriptEndColons = { link = "MedievalWhite" },
    typescriptDOMObjects = { link = "MedievalTan" },
    typescriptAjaxMethods = { link = "MedievalGreen" },
    typescriptLogicSymbols = { link = "MedievalRoyalRed" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "MedievalTan" },
    typescriptParens = { link = "MedievalWhite" },
    typescriptOpSymbols = { link = "MedievalWhite" },
    typescriptHtmlElemProperties = { link = "MedievalBlue" },
    typescriptNull = { link = "MedievalBlue" },
    typescriptInterpolationDelimiter = { link = "MedievalPurple" },
    typescriptTypeReference = { link = "MedievalRoyalBlueBold" },
    typescriptJSONStaticMethod = { link = "MedievalGreen" },
    typescriptMember = { link = "MedievalBlue" },
    -- purescript
    purescriptModuleKeyword = { link = "MedievalPurple" },
    purescriptModuleName = { link = "MedievalTan" },
    purescriptWhere = { link = "MedievalPurple" },
    purescriptDelimiter = { link = "None" },
    purescriptType = { link = "MedievalRoyalBlueBold" },
    purescriptImportKeyword = { link = "MedievalPurple" },
    purescriptHidingKeyword = { link = "MedievalPurple" },
    purescriptAsKeyword = { link = "MedievalPurple" },
    purescriptStructure = { link = "MedievalPurple" },
    purescriptOperator = { link = "MedievalBlue" },
    purescriptTypeVar = { link = "MedievalRoyalBlue" },
    purescriptConstructor = { link = "MedievalBronze" },
    purescriptFunction = { link = "MedievalGreen" },
    purescriptConditional = { link = "None" },
    purescriptBacktick = { link = "None" },
    -- coffescript
    coffeeExtendedOp = { link = "None" },
    coffeeSpecialOp = { link = "None" },
    coffeeCurly = { link = "None" },
    coffeeParen = { link = "None" },
    coffeeBracket = { link = "None" },
    -- ruby
    rubyStringDelimiter = { link = "None" },
    rubyInterpolationDelimiter = { link = "MedievalPurple" },
    rubyDefinedOperator = { link = "rubyKeyword" },
    -- objc
    objcTypeModifier = { link = "MedievalRoyalBlue" },
    objcDirective = { link = "MedievalBlue" },
    -- go
    goDirective = { link = "MedievalPurple" },
    goConstants = { link = "MedievalLightGreen" },
    goDeclaration = { link = "MedievalRoyalBlue" },
    goDeclType = { link = "MedievalBlue" },
    goBuiltins = { link = "None" },
    -- lua
    luaIn = { link = "MedievalRoyalBlue" },
    luaFunction = { link = "MedievalPurple" },
    luaTable = { link = "None" },
    -- moonscript
    moonSpecialOp = { link = "None" },
    moonExtendedOp = { link = "None" },
    moonFunction = { link = "None" },
    moonObject = { link = "MedievalRoyalBlue" },
    -- java
    javaAnnotation = { link = "MedievalBlue" },
    javaDocTags = { link = "MedievalPurple" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "None" },
    javaParen1 = { link = "None" },
    javaParen2 = { link = "None" },
    javaParen3 = { link = "None" },
    javaParen4 = { link = "None" },
    javaParen5 = { link = "None" },
    javaOperator = { link = "None" },
    javaVarArg = { link = "None" },
    -- elixir
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "None" },
    elixirInterpolationDelimiter = { link = "MedievalPurple" },
    elixirModuleDeclaration = { link = "MedievalRoyalBlue" },
    -- scala
    scalaNameDefinition = { link = "MedievalTan" },
    scalaCaseFollowing = { link = "MedievalTan" },
    scalaCapitalWord = { link = "MedievalTan" },
    scalaTypeExtension = { link = "MedievalTan" },
    scalaKeyword = { link = "MedievalRoyalBlue" },
    scalaKeywordModifier = { link = "MedievalRoyalBlue" },
    scalaSpecial = { link = "MedievalPurple" },
    scalaOperator = { link = "MedievalTan" },
    scalaTypeDeclaration = { link = "MedievalRoyalBlue" },
    scalaTypeTypePostDeclaration = { link = "MedievalRoyalBlue" },
    scalaInstanceDeclaration = { link = "MedievalTan" },
    scalaInterpolation = { link = "MedievalPurple" },
    -- markdown
    markdownItalic = { fg = palette.giantGreen, italic = true },
    markdownBold = { fg = palette.none, bold = config.bold },
    markdownBoldItalic = { fg = palette.none, bold = config.bold, italic = true },
    markdownH1 = { link = "MedievalRoyalBlueBold" },
    markdownH1Delimiter = { link = "MedievalRoyalBlueBold" },
    markdownH2 = { link = "MedievalRoyalBlueBold" },
    markdownH2Delimiter = { link = "MedievalRoyalBlueBold" },
    markdownH3 = { link = "MedievalRoyalBlueBold" },
    markdownH3Delimiter = { link = "MedievalRoyalBlueBold" },
    markdownH4 = { link = "MedievalRoyalBlueBold" },
    markdownH4Delimiter = { link = "MedievalRoyalBlueBold" },
    markdownH5 = { link = "MedievalRoyalBlueBold" },
    markdownH5Delimiter = { link = "MedievalRoyalBlueBold" },
    markdownH6 = { link = "MedievalRoyalBlueBold" },
    markdownH6Delimiter = { link = "MedievalRoyalBlueBold" },
    markdownCode = { link = "MedievalPurple" },
    markdownCodeBlock = { link = "MedievalPurple" },
    markdownCodeDelimiter = { link = "MedievalBronze" },
    markdownBlockquote = { link = "None" },
    markdownListMarker = { link = "MedievalBlue" },
    markdownOrderedListMarker = { link = "MedievalBlue" },
    markdownRule = { link = "None" },
    markdownHeadingRule = { link = "None" },
    markdownUrlDelimiter = { link = "None" },
    markdownLinkDelimiter = { link = "None" },
    markdownLinkTextDelimiter = { link = "None" },
    markdownHeadingDelimiter = { link = "None" },
    markdownUrl = { link = "MedievalLightGreen" },
    markdownUrlTitleDelimiter = { link = "None" },
    markdownLinkText = { fg = palette.none, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    -- haskell
    haskellType = { link = "MedievalBlue" },
    haskellIdentifier = { link = "MedievalPurple" },
    haskellSeparator = { link = "None" },
    haskellDelimiter = { link = "None" },
    haskellOperators = { link = "MedievalLightGreen" },
    haskellBacktick = { link = "None" },
    haskellStatement = { link = "MedievalLightGreen" },
    haskellConditional = { link = "MedievalLightGreen" },
    haskellLet = { link = "MedievalRoyalBlue" },
    haskellDefault = { link = "MedievalRoyalBlue" },
    haskellWhere = { link = "MedievalRoyalBlue" },
    haskellBottom = { link = "MedievalRoyalBlueBold" },
    haskellImportKeywords = { link = "MedievalElectricBlueBold" },
    haskellDeclKeyword = { link = "None" },
    haskellDecl = { link = "None" },
    haskellDeriving = { link = "MedievalLightGreen" },
    haskellAssocType = { link = "MedievalPurple" },
    haskellNumber = { link = "MedievalPurple" },
    haskellPragma = { link = "MedievalRoyalBlueBold" },
    haskellTH = { link = "MedievalPurpleBold" },
    haskellForeignKeywords = { link = "None" },
    haskellKeyword = { link = "MedievalRoyalBlue" },
    haskellFloat = { link = "MedievalPurple" },
    haskellInfix = { link = "MedievalLightGreen" },
    haskellQuote = { link = "None" },
    haskellShebang = { link = "MedievalWhiteBold" },
    haskellLiquid = { link = "MedievalElectricBlueBold" },
    haskellQuasiQuoted = { link = "MedievalBlueBold" },
    haskellRecursiveDo = { link = "MedievalLightGreen" },
    haskellQuotedType = { link = "MedievalRoyalBlue" },
    haskellPreProc = { link = "None" },
    haskellTypeRoles = { link = "MedievalRoyalBlueBold" },
    haskellTypeForall = { link = "MedievalRoyalBlue" },
    haskellPatternKeyword = { link = "MedievalBlue" },
    -- json
    jsonKeyword = { link = "None" },
    jsonQuote = { link = "None" },
    jsonBraces = { link = "MedievalWhite" },
    jsonString = { link = "MedievalLightGreen" },
    -- mail
    mailQuoted1 = { link = "MedievalPurple" },
    mailQuoted2 = { link = "MedievalLightGreen" },
    mailQuoted3 = { link = "MedievalRoyalBlue" },
    mailQuoted4 = { link = "None" },
    mailQuoted5 = { link = "MedievalRoyalBlue" },
    mailQuoted6 = { link = "None" },
    mailSignature = { link = "Comment" },
    -- c#
    csBraces = { link = "MedievalWhite" },
    csEndColon = { link = "MedievalWhite" },
    csLogicSymbols = { link = "MedievalRoyalRed" },
    csParens = { link = "None" },
    csOpSymbols = { link = "None" },
    csInterpolationDelimiter = { link = "None" },
    csInterpolationAlignDel = { link = "MedievalPurpleBold" },
    csInterpolationFormat = { link = "MedievalPurple" },
    csInterpolationFormatDel = { link = "MedievalPurpleBold" },
    -- rust btw
    rustSigil = { link = "None" },
    rustEscape = { link = "MedievalPurple" },
    rustStringContinuation = { link = "MedievalPurple" },
    rustEnum = { link = "MedievalPurple" },
    rustStructure = { link = "MedievalPurple" },
    rustModPathSep = { link = "None" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "MedievalPurple" },
    -- ocaml
    ocamlOperator = { link = "MedievalRoyalRed" },
    ocamlKeyChar = { link = "None" },
    ocamlArrow = { link = "None" },
    ocamlInfixOpKeyword = { link = "MedievalRoyalBlue" },
    ocamlConstructor = { link = "None" },
    -- lspsaga.nvim
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "MedievalSilver" },
    LspSagaCodeActionContent = { fg = palette.none, bold = config.bold },
    LspSagaLspFinderBorder = { link = "MedievalSilver" },
    LspSagaAutoPreview = { link = "None" },
    TargetWord = { fg = palette.none, bold = config.bold },
    FinderSeparator = { link = "MedievalPurple" },
    LspSagaDefPreviewBorder = { link = "MedievalBlue" },
    LspSagaHoverBorder = { link = "None" },
    LspSagaRenameBorder = { link = "MedievalBlue" },
    LspSagaDiagnosticSource = { link = "None" },
    LspSagaDiagnosticBorder = { link = "MedievalLightGreen" },
    LspSagaDiagnosticHeader = { link = "None" },
    LspSagaSignatureHelpBorder = { link = "None" },
    SagaShadow = { link = "None" },

    -- dashboard-nvim
    DashboardShortCut = { link = "None" },
    DashboardHeader = { link = "MedievalPurple" },
    DashboardCenter = { link = "MedievalRoyalBlue" },
    DashboardFooter = { fg = palette.none, italic = true },
    -- mason
    MasonHighlight = { link = "MedievalGreen" },
    MasonHighlightBlock = { fg = palette.broBronze, bg = palette.basementBlue },
    MasonHighlightBlockBold = { fg = palette.broBronze, bg = palette.basementBlue, bold = true },
    MasonHighlightSecondary = { fg = palette.none },
    MasonHighlightBlockSecondary = { fg = palette.none, bg = palette.none },
    MasonHighlightBlockBoldSecondary = { fg = palette.traditionalTan, bg = palette.basementBlue, bold = true },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonMuted = { fg = palette.semiSilver },
    MasonMutedBlock = { fg = palette.willingWhite, bg = palette.basicallyBlack },
    MasonMutedBlockBold = { fg = palette.none, bg = palette.none, bold = true },
    -- lsp-inlayhints.nvim
    LspInlayHint = { link = "comment" },
    -- carbon.nvim
    CarbonFile = { link = "MedievalTan" },
    CarbonExe = { link = "MedievalRoyalBlue" },
    CarbonSymlink = { link = "MedievalPurple" },
    CarbonBrokenSymlink = { link = "MedievalRoyalBlue" },
    CarbonIndicator = { link = "None" },
    CarbonDanger = { link = "MedievalRoyalRed" },
    CarbonPending = { link = "MedievalRoyalBlue" },
    -- noice.nvim
    NoiceCursor = { link = "TermCursor" },
    -- notify.nvim
    NotifyDEBUGBorder = { link = "MedievalBlue" },
    NotifyDEBUGIcon = { link = "MedievalBlue" },
    NotifyDEBUGTitle = { link = "MedievalBlue" },
    NotifyERRORBorder = { link = "MedievalRoyalRed" },
    NotifyERRORIcon = { link = "MedievalRoyalRed" },
    NotifyERRORTitle = { link = "MedievalRoyalRed" },
    NotifyINFOBorder = { link = "MedievalPurple" },
    NotifyINFOIcon = { link = "MedievalPurple" },
    NotifyINFOTitle = { link = "MedievalPurple" },
    NotifyTRACEBorder = { link = "None" },
    NotifyTRACEIcon = { link = "None" },
    NotifyTRACETitle = { link = "None" },
    NotifyWARNBorder = { link = "MedievalTan" },
    NotifyWARNIcon = { link = "MedievalTan" },
    NotifyWARNTitle = { link = "MedievalTan" },
    -- vim-fugitive
    fugitiveUnstagedHeading = { link = "MedievalPurple" },
    fugitiveStagedHeading = { link = "MedievalGreen" },
    fugitiveUnstagedModifier = { link = "MedievalRoyalRed" },
    fugitiveStagedModifier = { link = "MedievalLightGreen" },
  }

  for group, hl in pairs(config.overrides) do
    if groups[group] then
      -- "link" should not mix with other configs (:h hi-link)
      groups[group].link = nil
    end

    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

return M
